buses:
  source: NODE
  fields:
    id: NodeID
    x: CoordX
    y: CoordY
    feeder_id: NetworkID
    nominal_voltage_kv: DesiredVoltage
  defaults:
    nominal_voltage_kv: 22.9
lines:
  source: SECTION
  fields:
    id: SectionID
    from_bus: FromNodeID
    to_bus: ToNodeID
    length_km: Length
    type_id: LineCableID
    feeder_id: NetworkID
    nominal_voltage_kv: DesiredVoltage
  units:
    length_km: m
  defaults:
    nominal_voltage_kv: 22.9
sources:
  source: SOURCE
  fields:
    id: SourceID
    bus_id: NodeID
    nominal_voltage_kv: DesiredVoltage
loads:
  source: CUSTOMER_LOADS
  fields:
    id: DeviceNumber
    bus_id: ToNodeID
    active_power_mw: ActivePower_kW
    reactive_power_mvar: ReactivePower_kvar
  units:
    active_power_mw: kW
    reactive_power_mvar: kvar
target_crs: null
